// Mocks generated by Mockito 5.4.6 from annotations
// in task_6/test/feature/data/repositories/product_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:task_6/core/network/network_info.dart' as _i7;
import 'package:task_6/feature/data/datasources/product_local_data_source.dart'
    as _i6;
import 'package:task_6/feature/data/datasources/product_remote_data_source.dart'
    as _i4;
import 'package:task_6/feature/data/models/product_model.dart' as _i2;
import 'package:task_6/feature/domain/entities/product.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeProductModel_0 extends _i1.SmartFake implements _i2.ProductModel {
  _FakeProductModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProduct_1 extends _i1.SmartFake implements _i3.Product {
  _FakeProduct_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProductRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRemoteDataSource extends _i1.Mock
    implements _i4.ProductRemoteDataSource {
  @override
  _i5.Future<List<_i2.ProductModel>> fetchAll() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAll, []),
            returnValue: _i5.Future<List<_i2.ProductModel>>.value(
              <_i2.ProductModel>[],
            ),
            returnValueForMissingStub: _i5.Future<List<_i2.ProductModel>>.value(
              <_i2.ProductModel>[],
            ),
          )
          as _i5.Future<List<_i2.ProductModel>>);

  @override
  _i5.Future<_i2.ProductModel> fetchOne(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchOne, [id]),
            returnValue: _i5.Future<_i2.ProductModel>.value(
              _FakeProductModel_0(this, Invocation.method(#fetchOne, [id])),
            ),
            returnValueForMissingStub: _i5.Future<_i2.ProductModel>.value(
              _FakeProductModel_0(this, Invocation.method(#fetchOne, [id])),
            ),
          )
          as _i5.Future<_i2.ProductModel>);

  @override
  _i5.Future<void> create(_i2.ProductModel? product) =>
      (super.noSuchMethod(
            Invocation.method(#create, [product]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> update(_i2.ProductModel? product) =>
      (super.noSuchMethod(
            Invocation.method(#update, [product]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> delete(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [ProductLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductLocalDataSource extends _i1.Mock
    implements _i6.ProductLocalDataSource {
  @override
  _i5.Future<List<_i2.ProductModel>> getCachedAll() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedAll, []),
            returnValue: _i5.Future<List<_i2.ProductModel>>.value(
              <_i2.ProductModel>[],
            ),
            returnValueForMissingStub: _i5.Future<List<_i2.ProductModel>>.value(
              <_i2.ProductModel>[],
            ),
          )
          as _i5.Future<List<_i2.ProductModel>>);

  @override
  _i5.Future<_i2.ProductModel?> getCachedOne(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedOne, [id]),
            returnValue: _i5.Future<_i2.ProductModel?>.value(),
            returnValueForMissingStub: _i5.Future<_i2.ProductModel?>.value(),
          )
          as _i5.Future<_i2.ProductModel?>);

  @override
  _i5.Future<void> cacheAll(List<_i2.ProductModel>? products) =>
      (super.noSuchMethod(
            Invocation.method(#cacheAll, [products]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> cacheOne(_i2.ProductModel? product) =>
      (super.noSuchMethod(
            Invocation.method(#cacheOne, [product]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> removeCached(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeCached, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i7.NetworkInfo {
  @override
  _i5.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}

/// A class which mocks [ProductModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductModel extends _i1.Mock implements _i2.ProductModel {
  @override
  String get id =>
      (super.noSuchMethod(
            Invocation.getter(#id),
            returnValue: _i8.dummyValue<String>(this, Invocation.getter(#id)),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#id),
            ),
          )
          as String);

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i8.dummyValue<String>(this, Invocation.getter(#name)),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#name),
            ),
          )
          as String);

  @override
  String get description =>
      (super.noSuchMethod(
            Invocation.getter(#description),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#description),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#description),
            ),
          )
          as String);

  @override
  String get imageUrl =>
      (super.noSuchMethod(
            Invocation.getter(#imageUrl),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#imageUrl),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#imageUrl),
            ),
          )
          as String);

  @override
  double get price =>
      (super.noSuchMethod(
            Invocation.getter(#price),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  String get category =>
      (super.noSuchMethod(
            Invocation.getter(#category),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#category),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#category),
            ),
          )
          as String);

  @override
  double get rating =>
      (super.noSuchMethod(
            Invocation.getter(#rating),
            returnValue: 0.0,
            returnValueForMissingStub: 0.0,
          )
          as double);

  @override
  String get title =>
      (super.noSuchMethod(
            Invocation.getter(#title),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.getter(#title),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#title),
            ),
          )
          as String);

  @override
  Map<String, dynamic> toJson() =>
      (super.noSuchMethod(
            Invocation.method(#toJson, []),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i3.Product copyWith({
    String? id,
    String? name,
    String? description,
    String? imageUrl,
    double? price,
    String? category,
    double? rating,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#copyWith, [], {
              #id: id,
              #name: name,
              #description: description,
              #imageUrl: imageUrl,
              #price: price,
              #category: category,
              #rating: rating,
            }),
            returnValue: _FakeProduct_1(
              this,
              Invocation.method(#copyWith, [], {
                #id: id,
                #name: name,
                #description: description,
                #imageUrl: imageUrl,
                #price: price,
                #category: category,
                #rating: rating,
              }),
            ),
            returnValueForMissingStub: _FakeProduct_1(
              this,
              Invocation.method(#copyWith, [], {
                #id: id,
                #name: name,
                #description: description,
                #imageUrl: imageUrl,
                #price: price,
                #category: category,
                #rating: rating,
              }),
            ),
          )
          as _i3.Product);
}
